# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.2.1-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.12.2)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 585.9 kB/s eta 0:00:00
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 3.3 MB/s eta 0:00:00
Downloading cattrs-26.2.1-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 3.2 MB/s eta 0:00:00
Downloading url_normalize-3.0.1-py3-none-any.whl (18 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.2.1 chembl_webresource_client-0.10.9 requests-cache-1.3.3 url-normalize-3.0.1

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

/usr/local/lib/python3.13/dist-packages/chembl_webresource_client/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

## **Search for Target protein**

### **Target search for coronavirus**

In [3]:
# Target search for coronavirus
target = new_client.target
target_query = target.search('coronavirus')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Coronavirus,Coronavirus,17.0,False,CHEMBL613732,[],ORGANISM,11119
1,[],Feline coronavirus,Feline coronavirus,14.0,False,CHEMBL612744,[],ORGANISM,12663
2,[],Murine coronavirus,Murine coronavirus,14.0,False,CHEMBL5209664,[],ORGANISM,694005
3,[],Canine coronavirus,Canine coronavirus,14.0,False,CHEMBL5291668,[],ORGANISM,11153
4,[],Bovine coronavirus,Bovine coronavirus,14.0,False,CHEMBL6066646,[],ORGANISM,11128
5,[],Human coronavirus 229E,Human coronavirus 229E,13.0,False,CHEMBL613837,[],ORGANISM,11137
6,[],Human coronavirus OC43,Human coronavirus OC43,13.0,False,CHEMBL5209665,[],ORGANISM,31631
7,[],unidentified human coronavirus,unidentified human coronavirus,13.0,False,CHEMBL6195448,[],ORGANISM,694448
8,[],Human coronavirus NL63,Human coronavirus NL63,13.0,False,CHEMBL6195756,[],ORGANISM,277944
9,[],Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,9.0,False,CHEMBL4296578,[],ORGANISM,1335626
10,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,5.0,False,CHEMBL3927,"[{'accession': 'P0C6U8', 'component_descriptio...",SINGLE PROTEIN,694009
11,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1ab,4.0,False,CHEMBL5118,"[{'accession': 'P0C6X7', 'component_descriptio...",SINGLE PROTEIN,694009
12,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,4.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049
13,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon/Replicase polyprotein 1ab,4.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049
14,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,4.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049

### **Select and retrieve bioactivity data for *SARS coronavirus 3C-like proteinase* (fifth entry)**

We will assign the fifth entry (which corresponds to the target protein, *coronavirus 3C-like proteinase*) to the ***selected_target*** variable

In [6]:
selected_target = targets.target_chembl_id[10]
selected_target

'CHEMBL3927'

Here, we will retrieve only bioactivity data for *coronavirus 3C-like proteinase* (CHEMBL3927) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [7]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [8]:
df = pd.DataFrame.from_dict(res)

In [9]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5

In [11]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [12]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [15]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [16]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data2"

In [17]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [18]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

-rw------- 1 root root 156586 Oct 14 14:10 '/content/gdrive/My Drive/Colab Notebooks/data'

Let's see the CSV files that we have so far.

In [19]:
! ls

bioactivity_data.csv  gdrive  sample_data

In [20]:
ls -l

total 164
-rw-r--r-- 1 root root 156586 Oct 14 14:06 bioactivity_data.csv
drwx------ 6 root root   4096 Oct 14 14:08 gdrive/
drwxr-xr-x 1 root root   4096 Oct  2 13:50 sample_data/

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [21]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '18.28', 'le': '0.33', 'lle': '3.25', 'sei': '5.90'}",,CHEMBL187579,,CHEMBL187579,5.14,0,http://www.openphacts.org/units/Nanomolar,384103,=,1,1,=,,IC50,nM,,7200.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,7.2
,,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '12.10', 'le': '0.33', 'lle': '1.22', 'sei': '13.45'}",,CHEMBL188487,,CHEMBL188487,5.03,0,http://www.openphacts.org/units/Nanomolar,383984,=,1,1,=,,IC50,nM,,9400.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,9.4
,,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease) at 20 uM,B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '11.56', 'le': '0.29', 'lle': '2.21', 'sei': '8.72'}",,CHEMBL185698,,CHEMBL185698,4.87,0,http://www.openphacts.org/units/Nanomolar,384106,=,1,1,=,,IC50,nM,,13500.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,13.5
,,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.64', 'le': '0.32', 'lle': '1.25', 'sei': '13.06'}",,CHEMBL426082,,CHEMBL426082,4.88,0,http://www.openphacts.org/units/Nanomolar,384075,=,1,1,=,,IC50,nM,,13110.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,13.11
,,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.84', 'le': '0.32', 'lle': '2.16', 'sei': '7.08'}",,CHEMBL187717,,CHEMBL187717,5.70,0,http://www.openphacts.org/units/Nanomolar,384234,=,1,1,=,,IC50,nM,,2000.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,2.0
,,1481068,[],CHEMBL828143,In vitro inhibitory concentration SARS coronavirus main protease (SARS CoV 3C-like protease) ,B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.14', 'le': '0.37', 'lle': '1.62', 'sei': '16.07'}",,CHEMBL365134,,CHEMBL365134,6.01,0,http://www.openphacts.org/units/Nanomolar,384081,=,1,1,=,,IC50,nM,,980.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,0.98
,,1481088,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(F)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '17.08', 'le': '0.33', 'lle': '1.55', 'sei': '14.22'}",,CHEMBL187598,,CHEMBL187598,5.32,0,http://www.openphacts.org/units/Nanomolar,384303,=,1,1,=,,IC50,nM,,4820.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,4.82
,,1481089,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '14.36', 'le': '0.37', 'lle': '1.78', 'sei': '16.11'}",,CHEMBL190743,,CHEMBL190743,6.02,0,http://www.openphacts.org/units/Nanomolar,384329,=,1,1,=,,IC50,nM,,950.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,0.95
,,1481093,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2cccc(Cl)c21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '15.10', 'le': '0.31', 'lle': '0.67', 'sei': '13.24'}",,CHEMBL365469,,CHEMBL365469,4.95,0,http://www.openphacts.org/units/Nanomolar,384283,=,1,1,=,,IC50,nM,,11200.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,11.2

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [22]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5
3,None,None,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.11
4,None,None,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992024,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,48.0
260,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992025,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,20.0
261,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29103838,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6086440,Inhibition of SARS-CoV MPro using Dabcyl-KTSAV...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,0.053
262,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29103839,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6086440,Inhibition of SARS-CoV MPro using Dabcyl-KTSAV...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,0.04
263,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29103840,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6086440,Inhibition of SARS-CoV MPro using Dabcyl-KTSAV...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,170.0

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [23]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [24]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

In [25]:
mol_cid

['CHEMBL187579',
 'CHEMBL188487',
 'CHEMBL185698',
 'CHEMBL426082',
 'CHEMBL187717',
 'CHEMBL365134',
 'CHEMBL187598',
 'CHEMBL190743',
 'CHEMBL365469',
 'CHEMBL188983',
 'CHEMBL191575',
 'CHEMBL370923',
 'CHEMBL194398',
 'CHEMBL196635',
 'CHEMBL209287',
 'CHEMBL358279',
 'CHEMBL348660',
 'CHEMBL379727',
 'CHEMBL210525',
 'CHEMBL148483',
 'CHEMBL383725',
 'CHEMBL118596',
 'CHEMBL208732',
 'CHEMBL208732',
 'CHEMBL210146',
 'CHEMBL210146',
 'CHEMBL207458',
 'CHEMBL207458',
 'CHEMBL207484',
 'CHEMBL207484',
 'CHEMBL207207',
 'CHEMBL207207',
 'CHEMBL210487',
 'CHEMBL210487',
 'CHEMBL380470',
 'CHEMBL380470',
 'CHEMBL210612',
 'CHEMBL210612',
 'CHEMBL209667',
 'CHEMBL209667',
 'CHEMBL210097',
 'CHEMBL210097',
 'CHEMBL378674',
 'CHEMBL378674',
 'CHEMBL210216',
 'CHEMBL210216',
 'CHEMBL210195',
 'CHEMBL210195',
 'CHEMBL210437',
 'CHEMBL210437',
 'CHEMBL378677',
 'CHEMBL378677',
 'CHEMBL210972',
 'CHEMBL210972',
 'CHEMBL210145',
 'CHEMBL210145',
 'CHEMBL377225',
 'CHEMBL377225',
 'CHEMBL210823',
 'CHEMBL210823',
 'CHEMBL207381',
 'CHEMBL207381',
 'CHEMBL210511',
 'CHEMBL210511',
 'CHEMBL210632',
 'CHEMBL210632',
 'CHEMBL210497',
 'CHEMBL210497',
 'CHEMBL208584',
 'CHEMBL208584',
 'CHEMBL208763',
 'CHEMBL208763',
 'CHEMBL209227',
 'CHEMBL209227',
 'CHEMBL210092',
 'CHEMBL210092',
 'CHEMBL377150',
 'CHEMBL377150',
 'CHEMBL212454',
 'CHEMBL213581',
 'CHEMBL380403',
 'CHEMBL212504',
 'CHEMBL211969',
 'CHEMBL384739',
 'CHEMBL215732',
 'CHEMBL212240',
 'CHEMBL377253',
 'CHEMBL215397',
 'CHEMBL378342',
 'CHEMBL379642',
 'CHEMBL427404',
 'CHEMBL212190',
 'CHEMBL378700',
 'CHEMBL212019',
 'CHEMBL212399',
 'CHEMBL215733',
 'CHEMBL375130',
 'CHEMBL214372',
 'CHEMBL212218',
 'CHEMBL222840',
 'CHEMBL222769',
 'CHEMBL222735',
 'CHEMBL222628',
 'CHEMBL222893',
 'CHEMBL225515',
 'CHEMBL222234',
 'CHEMBL426898',
 'CHEMBL269277',
 'CHEMBL1448',
 'CHEMBL140',
 'CHEMBL395263',
 'CHEMBL242011',
 'CHEMBL431525',
 'CHEMBL258787',
 'CHEMBL2372143',
 'CHEMBL259622',
 'CHEMBL261189',
 'CHEMBL265704',
 'CHEMBL261402',
 'CHEMBL258581',
 'CHEMBL409422',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL523052',
 'CHEMBL495231',
 'CHEMBL468553',
 'CHEMBL222234',
 'CHEMBL1082811',
 'CHEMBL1082812',
 'CHEMBL1083123',
 'CHEMBL1083124',
 'CHEMBL1082714',
 'CHEMBL1082715',
 'CHEMBL327313',
 'CHEMBL1083958',
 'CHEMBL1083959',
 'CHEMBL1083286',
 'CHEMBL1082332',
 'CHEMBL1086234',
 'CHEMBL1082333',
 'CHEMBL1082334',
 'CHEMBL1084478',
 'CHEMBL1084479',
 'CHEMBL1084480',
 'CHEMBL1084481',
 'CHEMBL187266',
 'CHEMBL215254',
 'CHEMBL2146517',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL187266',
 'CHEMBL215254',
 'CHEMBL2146517',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL215254',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL187266',
 'CHEMBL215254',
 'CHEMBL2146517',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL18786',
 'CHEMBL2311740',
 'CHEMBL2311736',
 'CHEMBL2311734',
 'CHEMBL2311733',
 'CHEMBL2311732',
 'CHEMBL2311731',
 'CHEMBL2311730',
 'CHEMBL2311729',
 'CHEMBL2311727',
 'CHEMBL2311726',
 'CHEMBL2311709',
 'CHEMBL2311705',
 'CHEMBL2311700',
 'CHEMBL2311695',
 'CHEMBL2311694',
 'CHEMBL1405735',
 'CHEMBL2311693',
 'CHEMBL2311692',
 'CHEMBL2311691',
 'CHEMBL2397338',
 'CHEMBL2402686',
 'CHEMBL2402685',
 'CHEMBL2402680',
 'CHEMBL2402508',
 'CHEMBL2402501',
 'CHEMBL18786',
 'CHEMBL1929019',
 'CHEMBL2402692',
 'CHEMBL2402691',
 'CHEMBL406516',
 'CHEMBL2442082',
 'CHEMBL2442053',
 'CHEMBL2442054',
 'CHEMBL2442055',
 'CHEMBL2442056',
 'CHEMBL2442057',
 'CHEMBL2442058',
 'CHEMBL2442059',
 'CHEMBL2442061',
 'CHEMBL2442062',
 'CHEMBL2442063',
 'CHEMBL2442064',
 'CHEMBL2442065',
 'CHEMBL2442066',
 'CHEMBL2442067',
 'CHEMBL2442069',
 'CHEMBL2442073',
 'CHEMBL2442074',
 'CHEMBL2442075',
 'CHEMBL2442076',
 'CHEMBL2442077',
 'CHEMBL2442078',
 'CHEMBL2442079',
 'CHEMBL2440138',
 'CHEMBL2442080',
 'CHEMBL2311693',
 'CHEMBL18786',
 'CHEMBL2311692',
 'CHEMBL2442081',
 'CHEMBL4465864',
 'CHEMBL4532437',
 'CHEMBL4437284',
 'CHEMBL4459894',
 'CHEMBL18786',
 'CHEMBL4590273',
 'CHEMBL4590273',
 'CHEMBL5436771',
 'CHEMBL2365410',
 'CHEMBL5436771',
 'CHEMBL2365410',
 'CHEMBL5560356',
 'CHEMBL4850298',
 'CHEMBL3427166',
 'CHEMBL5593485',
 'CHEMBL5195325',
 'CHEMBL5564834',
 'CHEMBL218394',
 'CHEMBL2311740',
 'CHEMBL5563508',
 'CHEMBL5595277',
 'CHEMBL5570210',
 'CHEMBL5565685',
 'CHEMBL5565858',
 'CHEMBL4802135',
 'CHEMBL4796938',
 'CHEMBL4764751',
 'CHEMBL2022564']

### **Iterate *canonical_smiles* to a list**

In [26]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [27]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [28]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [ ]:
df3

    molecule_chembl_id  ... standard_value
0         CHEMBL187579  ...         7200.0
1         CHEMBL188487  ...         9400.0
2         CHEMBL185698  ...        13500.0
3         CHEMBL426082  ...        13110.0
4         CHEMBL187717  ...         2000.0
..                 ...  ...            ...
128      CHEMBL2146517  ...        10600.0
129       CHEMBL187460  ...        10100.0
130       CHEMBL363535  ...        11500.0
131       CHEMBL227075  ...        10700.0
132        CHEMBL45830  ...        78900.0

[133 rows x 4 columns]

### **Alternative method**

In [29]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0
...,...,...,...
259,CHEMBL5565858,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,48.0
260,CHEMBL4802135,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@...,20.0
261,CHEMBL4796938,O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC1CCCCC1...,53.0
262,CHEMBL4764751,O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](Cc1cccc(F...,40.0
263,CHEMBL2022564,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)O[C@H](C(...,170.0

In [32]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate
...,...,...,...,...
261,CHEMBL4796938,O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC1CCCCC1...,53.0,active
262,CHEMBL4764751,O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](Cc1cccc(F...,40.0,NaN
263,CHEMBL2022564,CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)O[C@H](C(...,170.0,NaN
220,NaN,NaN,NaN,inactive
222,NaN,NaN,NaN,intermediate

Saves dataframe to CSV file

In [33]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [34]:
! ls -l

total 184
-rw-r--r-- 1 root root 156586 Oct 14 14:06 bioactivity_data.csv
-rw-r--r-- 1 root root  20124 Oct 14 14:25 bioactivity_preprocessed_data.csv
drwx------ 6 root root   4096 Oct 14 14:08 gdrive
drwxr-xr-x 1 root root   4096 Oct  2 13:50 sample_data

Let's copy to the Google Drive

In [35]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [36]:
! ls "/content/gdrive/My Drive/Colab Notebooks/data"

'/content/gdrive/My Drive/Colab Notebooks/data'

---